blank_issues_enabled: false
contact_links:
  - name: Contacto Puente Impacto
    url: https://puenteimpacto.org/contacto
    about: Para contacto institucional o colaboraciones.
  - name: Agendar reuni&oacute;n
    url: https://calendly.com/contacto-puenteimpacto/30min
    about: Agenda una reuni&oacute;n general de 30 minutos.
